name: build_all # workflow名称

on: # 触发条件
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 是否手动触发部署
  workflow_dispatch:

jobs:
  build_all:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）
    steps:
      - uses: actions/checkout@master
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      # 运行构建脚本 yarn docs:build
      - name: Build site admin
        run: sh deploy-admin.sh
        
      - name: Build site hack
        run: sh deploy-hack.sh
        
      - name: add home
        run: |
            cp _config.yml deploy
            cp README.md deploy
            
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: deploy
          