name: deploy # workflow名称

on: # 触发条件
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [release]
  # 是否手动触发部署
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）
    steps:
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: deploy